### ISSUE TITLE
Add support for leading zeros in image index

### ISSUE THREAD

**Issue by Ealdst** [rajeevgade/vue-360#1]
Hi,

I was experimenting with your component but could not get it to work, I then noticed I had an issue where the images from my organisation are using a minimum of 2 characters for the index (eg. image-01.jpg, image-02.jpg.....image-10.jpg etc). It is out of my control to change the file names so would you consider adding the ability to pad the index with leading zeros via an optional property?

**Comment by rajeevgade** [comment]
Hi @Ealdst,

I've added the pad support for leading zeros as requested. Pushed it to the master branch. Let me know if it is working for you. Thanks and have fun.

**Comment by Ealdst** [comment]
Thanks for the really quick response on this. Working perfectly!

**Comment by rajeevgade** [comment]
Awesome!
