### ISSUE TITLE
use photos from public folder

### ISSUE THREAD

**Issue by thelittlejuan** [rajeevgade/vue-360#12]
Hello, I am beginer, how can I access to the potos inside of public folder for photos in a local enviroment not cloud?

Is something like this:
imagePath="../public"
fileName="{index}.png"

Thank you

**Comment by rajeevgade** [comment]
@thelittlejuan there are different ways you can do this. you can use `path` package that is pre-built in node.js to achieve this. Hopefully, you figured it out by now. Sorry for the late reply and Thanks for using the component.
