### ISSUE TITLE
Documentation for contribution

### ISSUE THREAD

**Issue by marius321967** [rajeevgade/vue-360#2]
I wish to contribute to the project but there is no documentation on how to compile the Vue plugin (index.js). Running `bili` does not produce the same result as the installed npm package.

**Comment by rajeevgade** [comment]
Hi Marius,

Sorry about that. It was my first npm package and I forgot to add the documentation for how to build the npm package using bill. I did follow a few articles at the time.

[How to build your first package and publish it on npm](https://www.telerik.com/blogs/vuejs-how-to-build-your-first-package-publish-it-on-npm)

This is one of the article I followed for building the npm package and the command I used for that is
`npx bili --bundle-node-modules`

Thanks for your interest. Let me know if you get any other issues. :)

**Comment by marius321967** [comment]
Great! Thank you for the help. I will submit a PR if I find anything to contribute. ;)
