### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Redrica** [rajeevgade/vue-360#6]
Hi! 
I tried to install package using `npm i vue-360`, in node_modules appeared a folder "vue-360" with it's own "node-modules", package.json, etc. No "dist" or something like that. What have I done wrong?
Thanks in advance.

**Comment by rajeevgade** [comment]
Hi Redrica, 

Thank you for pointing it out. Looks like something went wrong with the bundler when i released the latest version. If you need it right away, you can use 0.1.1 version which shouldn't have any problems. (npm i vue-360@0.1.1). I will work on fixing the latest version and let you know once i'm done with it.

**Comment by Redrica** [comment]
Hi rajeevgade! 
Thanks for update. I tried to install it again, dist folder appeared but now it includes only one file index.js. In config you wrote about css/style.css but I dont see it. Maybe something went wrong again?
This is what I see after installation http://prntscr.com/ujdql4

**Comment by rajeevgade** [comment]
Hi Redrica,

Sorry about that! I forgot to run `npm run build` before running the bundler. 

Try running it again now! The asset files should be included in the dist folder now.

Let me know if it breaks again.

Thank you!
