### ISSUE TITLE
is it possible on mousewheel function to  turn image instead of zoom? Thanks.. 

### ISSUE THREAD

**Issue by shejin-abu5** [rajeevgade/vue-360#9]

**Comment by rajeevgade** [comment]
@shejin-abu5 Right now it isn't possible, but i have added it to my future roadmap. Hopefully i can find time to work on it and release it in this month. Will keep you posted. Thanks :)

**Comment by rajeevgade** [comment]
@shejin-abu5 Test out the latest version i just published and let me know if that works for you. Thanks :)
